"""add payment_intent_id to orders

Revision ID: e6b5ee7a2bcd
Revises: 
Create Date: 2026-05-13 00:59:28.024654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b5ee7a2bcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_payment_intent_id'), ['payment_intent_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_payment_intent_id'))
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
